# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kairo < Formula
  desc "Minimal, powerful task management"
  homepage "https://github.com/programmersd21/kairo"
  version "1.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/programmersd21/kairo/releases/download/1.4.2/kairo_darwin_x86_64.tar.gz"
      sha256 "a31d00990f5e40b150ccb391c3cbb0ba48f913bbb8b9766c206b72631c52878b"

      define_method(:install) do
        bin.install "kairo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/programmersd21/kairo/releases/download/1.4.2/kairo_darwin_arm64.tar.gz"
      sha256 "f99048dd5d5e4ec634615c1690380366989e691790788e8049d4abc98676d313"

      define_method(:install) do
        bin.install "kairo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/programmersd21/kairo/releases/download/1.4.2/kairo_linux_x86_64.tar.gz"
      sha256 "183438cf466172b714459fe9b753940fe656cb18d4d111efc8a9923099dc7e6e"
      define_method(:install) do
        bin.install "kairo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/programmersd21/kairo/releases/download/1.4.2/kairo_linux_arm64.tar.gz"
      sha256 "1754ab28ab04b9694c0543ee4d8387c6bfcd631e81a1d8f4230eb38e29a99f58"
      define_method(:install) do
        bin.install "kairo"
      end
    end
  end

  test do
    system "#{bin}/kairo", "--version"
  end
end
